### PR TITLE
fix entity encoding of ampersand

### PR DESCRIPTION
**Pull request by ckuethe**

### CODE REVIEW

**Comment by johschmitz** [comment]
Can you give a short explanation of the change? I am not very familiar with the grc details as I am mostly directly working with python and c++. Why is the ampersand (&) necessary at all? I don't find that in the documentation. I believe we just added the XML blocks using gr-modtool, so most likely it comes from that.

**Comment by ckuethe** [comment]
screenshot_2016-07-14_09-38-20

**Comment by ckuethe** [comment]
http://www.techrepublic.com/article/beware-of-the-ampersand-when-using-xml/

I can't find a handy reference right now for the syntax of the parameters, but if modtool is generating invalid XML I'll send a fix upstream.

**Comment by johschmitz** [comment]
I am just unsure if we can remove the & or if I should apply your patch.
Because I tried to check some other examples an didn't see &s? Just trying
to follow best practices. What exactly made you come up with this specific
solution? Or just trial and error?
If you say it's absolutely necessary and works I will merge it.
I just don't know exactly what the &  syntax means here.
Am 14.07.2016 7:29 nachm. schrieb "ckuethe" notifications@github.com:

**Comment by ckuethe** [comment]
Here are the [gr_modtool templates](https://github.com/gnuradio/gnuradio/blob/64a702e19d1e8e1b948e6ef76e98dff41837bb92/gr-utils/python/modtool/templates.py). 

[OutOfTreeModules](http://gnuradio.org/redmine/projects/gnuradio/wiki/OutOfTreeModules#Making-your-blocks-available-in-GRC) says that the file needs to be "valid XML" - because of that ampersands need to be encoded.

I haven't found an authoritative reference that says the ampersand is meaningful; perhaps the ampersands could be removed entirely if gr_modtool is naively dropping your C++ function signature into the template. Could you remove the ampersands from the XML and see if your flowgraphs still work?

**Comment by johschmitz** [comment]
Thing is I am not using the XML version of the blocks at all. We added
added them for convenience. Don't you maybe have it still running
somewhere? It would take me a lot of time to check but I don't mind waiting
for a week if you have a simple possibility to check it.
If it's too much of a hassle, never mind.
Am 14.07.2016 9:27 nachm. schrieb "ckuethe" notifications@github.com:

Here are the gr_modtool templates
https://github.com/gnuradio/gnuradio/blob/64a702e19d1e8e1b948e6ef76e98dff41837bb92/gr-utils/python/modtool/templates.py.

OutOfTreeModules
http://gnuradio.org/redmine/projects/gnuradio/wiki/OutOfTreeModules#Making-your-blocks-available-in-GRC
says that the file needs to be "valid XML" - because of that ampersands
need to be encoded.

I haven't found an authoritative reference that says the ampersand is
meaningful; perhaps the ampersands could be removed entirely if gr_modtool
is naively dropping your C++ function signature into the template. Could
you remove the ampersands from the XML and see if your flowgraphs still
work?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
https://github.com/rwth-ti/gr-ofdm/pull/1#issuecomment-232767255, or mute
the thread
https://github.com/notifications/unsubscribe/AAvHiyrCUgT9nU116B6kaliJyWc8HqzGks5qVo21gaJpZM4JL9op
.

**Comment by ckuethe** [comment]
I would check but I don't have any ALE recordings. I just found your module and haven't yet had a chance to use it with any real signals.

**Comment by johschmitz** [comment]
Ah, never mind you can directly connect tx and rx like we do in the
benchmark file.
Try running the simulated system on one machine as described in the README.
Basically just call that script that starts everything from the apps
folder. Should be quite simple.
Drop me an email if you have any problems.
Email ID should be in the README as well.
Am 14.07.2016 9:47 nachm. schrieb "ckuethe" notifications@github.com:

**Pull request merged**
